# frozen_string_literal: true

require "bundler/gem_tasks"
require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

desc "Build the native extension"
task :build_ext do
  sh "zig build"
end

desc "Clean build artifacts"
task :clean do
  sh "rm -rf zig-out .zig-cache"
end

task default: [:build_ext, :test]
